### ISSUE TITLE
Introduce new config option `ClusterCheckinMisfireThreshold`

### ISSUE THREAD

**Issue by footcha** [quartznet/quartznet#692] opened 2018-10-10 06:00 UTC
### Expected behavior

Clustered check-in can be missed due to ```GC.Collect()``` taking extraordinary long time - the cluster instance is "frozen". When garbage collector finishes its work then a scheduler instance is "unfrozen" and continues its regular work. However, there is a chance that in the meantime another cluster instance can detect the "frozen" instance as failed and clears it. After garbage collecting period, when the first instance is unfreezed and it detects "This scheduler instance (xxx) is still active but was recovered by another instance in the cluster. This may cause inconsistent behavior."
As a consequence, jobs marked with ```DisallowConcurrentExecutionAttribute``` do run in parallel among cluster instances.

It cannot be simply fixed by a greater value in ```quartz.jobStore.clusterCheckinInterval```. I suggest a new configuration option ```quartz.jobStore.clusterCheckinMisfireThreshold```. The sum of clusterCheckinInterval and clusterCheckinMisfireThreshold then will be the "maxNotResponding" interval for a scheduler instance - if it exceedes then other scheduler instances can consider this scheduler instance as failed.

**Comment by lahma** [comment] 2018-10-10 06:08
Interesting analysis, thanks for digging into this. I would love to get a PR showing the concept and ideally keeping the old behavior as intact as reasonable (maybe opt-in new behavior?).

Another thing is what might be the root cause for such long pause - how long pause are we talking about? Is Quartz generating the the GC stress or your jobs?

**Comment by footcha** [comment] 2018-10-10 06:45
> Another thing is what might be the root cause for such long pause - how long pause are we talking about? Is Quartz generating the the GC stress or your jobs?

I believe that image https://pasteboard.co/HHLs93x.png will help to understand my proposal. If there is a delay in regular clustered chechin (due to garbage collector, network latency, etc.) then there should be additional protection period (clusterCheckinMisfireThreshold) that discourages other scheduler instances from detecting this scheduler instance as failed.
In practice we have raher long ```GC.Collect()``` period (can be 150sec in some cases). Quartz is not to blame - Quartz is just a victim of such an extraordinary behaviour.

**Comment by lahma** [comment] 2018-10-10 06:55
OK thanks for the clarification. The 150sec is a really long pause indeed. Thanks for bringing this into attention and also providing a solution. Will be part of the next release!

**Closed by lahma** 2018-10-10 06:55 UTC

**Comment by adansklevanskis** [comment] 2019-08-09 20:15
Hi lahma,
Can you say when this change will be published as a new version of Nuget package? 
Thanks!

**Comment by lahma** [comment] 2019-08-12 19:01
@adansklevanskis sorry to keep you hanging, I've been busy with life and hopefully I can finalize some things for 3.1 in the near future. You can always use the [MyGet feed](https://www.myget.org/F/quartznet/api/v3/index.json) though.
