### ISSUE TITLE
HTTP based API

### ISSUE THREAD

**Issue by lahma** [quartznet/quartznet#511] opened 2017-08-16 15:09 UTC
# Background

Quartz used to have a remote interface based on .NET remoting that allowed controlling scheduler via remote calls. Remoting has been deprecated and is no longer available on .NET Core / .NET Standard. To allow such remote controlling we need a more standard HTTP based API that allows to perform the functionality offered by IScheduler.

# Requirements

* Quartz core (Quartz.dll) should not get new "non-standard" dependencies, everything from System.* is fine
  * we want Quartz to stay as small as possible, dependency-wise
* Should be able to perform same things as with 2.x remoting based API

# Architecture / Design

* Two parts, server and client
  * can be two separate projects, pulled in via NuGet

* Ideally the two share contract via PONOs, internal classes
* Server
   * A plugin to Quartz that allows hosting of RESTish API, configured as scheduler plugin
      * customizable ports
      * authentication (API key, HTTP Basic could be a good start)
      * HTTPS support to secure authentication exchange
   * Kestrel, .NET Core 2 supported at least
   * Swagger as documentation tool?
* Client
   * IScheduler, or similar interface, that uses HTTP calls behind the scenes
* Fluent configuration later on, to allow idiomatic configuration

**Comment by SeanFarrow** [comment] 2017-08-17 15:22
We should probably add some retry logic to the clients.
Also, what authentication do we want to support?
Should we separate clients for jobs/schedules etc?

**Comment by lahma** [comment] 2017-08-26 10:23
@SeanFarrow I updated the description a bit

> The clients should probably separate from Quartz itself.

Agree 

> We should probably add some retry logic to the clients using something like polly?

I think that this can be done later or even be caller side

> Also, what authentication types do we want to support?

Added API key and HTTP basic for starters, HTTPS would be nice

> Should we separate clients for jobs/schedules etc?

I guess most of IScheduler controls the scheduler so I don't directly see need to spread functioanlity between client interfaces

> Should we allow supporting multiple schedulers using one API?

One might construct API instance giving all the required details?

**Comment by eugenej** [comment] 2018-03-24 00:57
I wonder if method to retrieve list of all available IJob implementations on Quartz Server can be included in this new Api. That way you can pull list of possible jobs from server and you will know upfront if you can schedule it or not. 

Additionally come up with ability to add metadata (possible job map properties for specific IJob implementation), so it can be returned along with list of possible jobs.

**Comment by puddlewitt** [comment] 2018-09-24 08:43
Would we have to worry about authentication? If added this as another middleware downstream of any other auth? I guess the idea would be to allow the consumer to decide upon the auth.

Something like...

```csharp
services.AddAuthentication()
services.AddCookie()
services.AddOpenIdConnect()
services.AddOAuthIntrospection()
services.AddQuartz(Func<Context, bool> authCallBack)

app.UseAuthentication();
app.UseQuartz();
```

**Comment by SeanFarrow** [comment] 2018-09-24 09:34
Ideally, no.
There would just be a UseQuartz method as you described below.

**Comment by jwheatle** [comment] 2019-03-21 14:46
Is there any timeline for supporting Quartz.Net remoting features in .Net Core?

Our project currently uses Quartz.Net remoting features but we have to convert to .Net Core by June 2019.  We are trying to determine whether we should design our own alternative for remote calls to Quartz.Net.

**Comment by SeanFarrow** [comment] 2019-03-21 15:13
@, jwheatle

Nothing has been done on this as yet, what sorts of things would you want in an API?

**Comment by jwheatle** [comment] 2019-03-21 16:40
Ideally, something where the configuration properties have different values but the scheduler API calls remain unchanged would be nice.

NameValueCollection properties = new NameValueCollection
{
    { "quartz.scheduler.instanceName",  "RemoteClient" },
    { "quartz.threadPool.type", "Quartz.Simpl.SimpleThreadPool, Quartz" },
    { "quartz.threadPool.threadCount", "10" },
    { "quartz.scheduler.proxy", "true" },
    { "quartz.scheduler.proxy.address", "http://127.0.0.1:555/QuartzScheduler" }
};

var sf = new StdSchedulerFactory(properties);
var scheduler = sf.GetScheduler();

if (scheduler != null)
{
    var exists = await scheduler.CheckExists(new JobKey("JOB001"));
}

We currently have our own service that runs on a single server and handles starting the Quartz.Net scheduler and responding to triggers that fire.  Our client app uses the remoting features to make Quartz.Net API calls for scheduling jobs, etc. as though the Quartz processing were local.  All of our Quartz.Net configuration and usage is done programmatically.

The alternative we are considering would be to use our own existing client-server communication packets and have the client app sent the desired API function name and arguments to our service, which would then execute the API function locally and send a response packet containing the result back to the client app.  This sounds straight forward but would likely have some complicated details.

**Comment by SeanFarrow** [comment] 2019-03-21 16:46
That makes sense, however I think the original proposal was to have an http API for actually scheduling jobs/triggers.
From what you are saying, you want a scheduler that can interact with either a remote instance of quartz directly, or an API of some form—correct me if I’m wrong!

**Comment by jwheatle** [comment] 2019-03-21 17:02
I'm not requesting that it be any certain way, but ideally it would be nice if we could continue using Quartz.Net with .Net Core the way we are already using it with .Net Framework.

For .Net Framework, the current API already supports a scheduler that can interact with a local or remote instance of Quartz without changing anything but the configuration properties and how the reference to the scheduler is obtained.  **Is this the "remoting" feature that is incompatible with .Net Core?**

**Comment by lahma** [comment] 2019-03-21 17:10
Ideally this will give both IScheduler interface (proxy) and the RESTish API. One would configure remote HTTP and get the same experience as with remoting, if even better.

**Comment by jwheatle** [comment] 2019-03-21 17:13
Is the proxy usage I described above currently compatible with .Net Core?

**Comment by jwheatle** [comment] 2019-03-22 22:18
I created a .Net Core application and confirmed for myself that the remote proxy usage does not work in .Net Core.

Is there any idea of a timeline for supporting the remote proxy usage in .Net Core?  We are trying to decide whether to wait for this feature, design an alternative solution, or possibly design a temporary workaround until this feature is ready.

The reason we are converting our projects to .Net Core is so they will run in Linux containers with Docker.

**Comment by SeanFarrow** [comment] 2019-03-23 03:40
I don’t have a timeframe—but I’m notgoing to be doing anything before the beginning of the week after next.
Could you not run the existing quartz apps in a windows container as a work around, for now at least?
Cheers
Sean.

**Comment by relawson** [comment] 2019-03-28 13:27
I'm glad I found this thread because I am currently trying to figure this problem out with .Net Core.  Perhaps the documentation on remoting should clearly state that .net core is not currently supported - would save people time.  

I also want to point out one other issue.  My intent was to have a proxy server that can be deployed to the cloud.  However, Azure App Services only allows ports 80 and 334 over http or https protocols.  So TCP over any other port (555) won't work with App Services.  It would simplify deployments if we were simply making http requests.   Because it appears that you are rethinking the architecture I thought that is something that you should also consider.

**Comment by jwheatle** [comment] 2019-03-28 15:20
For our project, we have decided to proceed with an alternative solution using our existing client-server communication to handle remote scheduler usage.  Our main reason for this is our deadline of June 2019.  Another reason is that our existing client-server communication handles routing to a different fallback server when necessary.

We may still use the the remoting features for other projects in the future.  The remoting features worked great with .Net Framework and allowed us to use the same code for both local and remote schedule usage once we had a reference to the scheduler.

**Comment by SeanFarrow** [comment] 2019-03-28 15:22
Assuming this was an http-based API, would you want to use queues on the back-end or are you happy with the API communicating with quartz directly?

**Comment by jwheatle** [comment] 2019-04-04 16:20
I'm not sure what you mean by queues on the back-end.  Our only usage of the remote features involved using IScheduler, which with certain configuration property values would allow its methods to be called the same way regardless of whether the scheduler were running locally or remotely.

**Comment by SeanFarrow** [comment] 2019-04-06 14:52
What I meant was do you want the API to call the scheduler directly, or place a message in a queue with a backend service collecting them and calling the scheduler?

**Comment by StrongGesmbH** [comment] 2019-09-03 06:35
I am working on a web api for the Scheduler.
The first release will only contain scheduler functions but i will continue to cover jobs,triggers and calendars.
It is based on that you have one server with possibility for multiple schedulers on the same server.

Im also working on a realtime dashboard for the scheduler but there are no plans currently to release this as open source.
![SchedulerDashboard](https://user-images.githubusercontent.com/45846979/64149249-b9edec00-ce25-11e9-8497-489acdfb74bc.png)
![SchedulerOverView](https://user-images.githubusercontent.com/45846979/64149262-c1ad9080-ce25-11e9-8ebf-2282904315da.png)

**Comment by Sicos1977** [comment] 2019-09-03 09:01
Why mention it when you don't are planning to make it opensource?

**Comment by StrongGesmbH** [comment] 2019-09-03 14:44
The api will be open  source.

**Comment by gwinnem** [comment] 2019-09-13 12:22
Initial commit to the web api is ready so check it out at:
https://github.com/gwinnem/AB.QuartzAdmin.WebApi
This first commit contains a example project and the api project with the scheduler endpoints completed.

Feedback in any form is always appreciated.
![SchedulerApiEndpoint](https://user-images.githubusercontent.com/6427120/64862068-e548b600-d631-11e9-8c02-4db3e63ade96.png)

**Comment by liaowubinf** [comment] 2020-06-19 01:58
> The api will be open source.
When? A year has passed

**Comment by liaowubinf** [comment] 2020-06-19 02:00
> The api will be open source.

When?  A year has passed

**Comment by lahma** [comment] 2020-07-15 15:40
I've played around the idea and now I'm considering the following:

* Middleware in [Quartz.AspNetCore](https://www.quartz-scheduler.net/2020/07/08/quartznet-3-1-beta-1-released/), which hosts the API, configurable prefix (defaults probably to /quartz/api)
    * Middleware can be embedded to on ASP.NET Core project
* Separate plugin that allows starting the API as part of an exe process, will basically start ASP.NET Core host

**Comment by lahma** [comment] 2020-07-15 15:43
@liaowubinf we accept pull requests to help out if you are in a hurry.

**Comment by CrossBound** [comment] 2020-11-18 21:36
Just found this thread and I have to say I think it's a great idea. 

In my case I'm trying to do the exact  same thing. I want an NT Service running which will be executing the jobs and I want a separate admin web API which allows IT staff to manage the job schedules. 

Maybe if I get something working my boss will let me contribute it.

**Comment by lahma** [comment] 2020-11-19 05:50
Contributions are always welcome! It took a sizeable amount of my time when I did the last sprint (new web page, new IoC integration packages etc) so I had to choose where to put the efforts. This feature is something that would be nice and doable also in 3.x timeframe.

**Comment by zihotki** [comment] 2021-07-29 09:42
Greetings, at my current employer we are going to use Quartz for a job server and we are going to work on API and UI for managing the jobs. So we may actually provide some bit of help in this regards. Looking at the earlier discussion and current state of .Net I would like to suggest the following:

* Use at lease Asp.Net Core 3.1 since v2.* reaches end of life this August
* Leave authentication aside as well as Open Api since in newer version there is an easier way of sharing the api, please refer to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#guidance-for-library-authors . Nowadays setup of Auth and Open Api should be done in the application itself. And after the configuration of Open Api UI, the Quartz API should be available there out of the box. There may be some dragons but it should still be possible to achieve that.
* Provide a library that has necessary extension methods to setup the Quartz API
* Optionally provide a similar library for job status polling based on SignalR
* Provide a sample App that uses the libraries

So at the end the scope of work would be significatnly smaller and using prior work for API it should be easy to implement it. But in order to implement it there is one big pain point in the Quartz.Net - there is no paging in methods which could potentially return thousands items. So overloads for methods to accept paging parameters should be implemented as well. I suggest to use similar to LINQ parameters - take and skip, both optional (I will create a ticket and a PR if it's a good idea).

On another hand, current Quartz API is not very suitable for GET endpoints. It's quite cumbersome to implement filtering and ordering using it. It would be much easier to do that if there was a LINQ layer available, of course only for reading data and throw when modification is requested. That way it will be possible to map GET parameters to expression tree and get filtering-sorting out of the box, I have a library which may help with that. As for mutation endpoints, those should use standard methods.

So what do you think?

**Comment by SeanFarrow** [comment] 2021-07-29 10:30
Hi,

Whilst this all sounds reasonable to me, I wonder whether we should use Open API to design the API before implementation?
That way, non-.Net clients would have an easy way to consume whatever is built.

I agree authorization and authentication should be left out.

Paging and filtering are definitely concerns we need to address. What library do you have that could help with this?

Thanks,
Sean.

**Comment by lahma** [comment] 2021-07-29 12:24
@zihotki this is great news, it would be great if you can kickstart the thing. I'll check what is the status of the work I initially started and push it so if there's anything of use.

> * Use at lease Asp.Net Core 3.1 since v2.* reaches end of life this August

Yes we can require 3.1.

> * Leave authentication aside as well as Open Api since in newer version there is an easier way of sharing the api, please refer to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#guidance-for-library-authors . Nowadays setup of Auth and Open Api should be done in the application itself. And after the configuration of Open Api UI, the Quartz API should be available there out of the box. There may be some dragons but it should still be possible to achieve that.

One idea was that this could be just a middleware that would be in pipeline and thus authentication/authorize can happen as configured. This can conflict with the idea of easiest possible and/or easy generation of swagger clients though...

> * Provide a library that has necessary extension methods to setup the Quartz API

Yes, something like AddQuartz and UseQuartz, the idiomatic ASP.NET Core way.

> * Optionally provide a similar library for job status polling based on SignalR

Sounds good, not required for minimum viable, but if it's in your requirements, I don't complain.

> * Provide a sample App that uses the libraries

Definitely yes. The current ASP.NET Core sample probably could be morphed into this as it now demonstrates the registration and has very simple and silly UI to show what's happening. Remote client project is a different thing.

> So at the end the scope of work would be significatnly smaller and using prior work for API it should be easy to implement it. But in order to implement it there is one big pain point in the Quartz.Net - there is no paging in methods which could potentially return thousands items. So overloads for methods to accept paging parameters should be implemented as well. I suggest to use similar to LINQ parameters - take and skip, both optional (I will create a ticket and a PR if it's a good idea).

The REST(ish) API can probably start with ideal query and paging models (page 1, count 25) and backend unfortunately does in-memory limiting and later something more clever when `AdoJobStore` allows limiting results. `RAMJobStore` shouldn't be a problem here.

> On another hand, current Quartz API is not very suitable for GET endpoints. It's quite cumbersome to implement filtering and ordering using it. It would be much easier to do that if there was a LINQ layer available, of course only for reading data and throw when modification is requested. That way it will be possible to map GET parameters to expression tree and get filtering-sorting out of the box, I have a library which may help with that. As for mutation endpoints, those should use standard methods.

To integrate with Quartz v3, I think there needs to be the RemoteScheduler thingie that does those costly calls. The filtering currently has to be done using `GetJobKeys` and `GetTriggerKeys` kind of methods that take a matcher.

**Comment by lahma** [comment] 2021-07-29 13:39
@zihotki [I've pushed the first iteration](https://github.com/quartznet/quartznet/compare/http-api?expand=1) I made, nothing binding here, just showing some concepts:

* It's a plugin `HttpApiPlugin` in it's current state, creates a separate web host, might or might not be ideal but a way to host the API even if not an ASP.NET Core project is consuming
* `HttpSchedulerProxyFactory` is the glue for HTTP communication like `RemotingSchedulerProxyFactory` is for remoting
     *  I know `IRemotableQuartzScheduler` API is horrible (looks like local calls), but something to live with if wanted to target Quartz 3, remote calls never had any API tweaks since the beginning...
     *  HTTP API can be as fancy and REST as needed, but ideally this can (and needs to) call it "in a bad way", like page 1, count =   int.MaxValue to fulfil current contract
     *  this is basically the only "UI" that Quartz as a library needs, then there's all the fanciness like actual HTML UI, maybe reusing existing work 
* API contracts as DTO files, probably would need some more love with paging like said, but could fulfil the itch 
* Uses controllers so requires the whole ASP.NET Core stack, which might not be ideal, vs. the middleware handling request/response

I'd also suggest checking the existing work like [CrystalQuartz](https://github.com/guryanovev/CrystalQuartz) and [Quartzmin](https://github.com/jlucansky/Quartzmin), how they plug their API. 

I'm glad for any progress, doesn't need to follow the initial work I did, but it would be great to follow the work in progress via a possible PR. Also more aggressive API changes can be done if target is Quartz 4.

**Comment by tonyqus** [comment] 2022-05-08 19:35
What's the status of this issue? Have you implemented Http API? 

I'm scheduling my open source contribution for different projects (instead of just projects owned by me) this year. Do you need a hand for this?

**Comment by adurmus** [comment] 2022-08-15 08:51
@lahma is there any work done for this? Is it possible to use remote client in `.net 6`?

**Comment by Sicos1977** [comment] 2022-08-15 10:07
I started building a webapi but I did not have any time last month because of work. I hope to pick it up again this week.

https://github.com/Sicos1977/QuartzWebApi

**Comment by adurmus** [comment] 2022-08-15 10:23
@Sicos1977  this is interesting. I haven't checked all but I was looking something more a middleware implementation that can be attached into an existing .net core( .net 5 -6 -7) application. This would bring all features in automatically. I wonder how this would be configured to communicate with a Window Service (.exe)?

**Comment by Sicos1977** [comment] 2022-08-15 10:30
I'm going to make it hostable in IIS or self hosted with owin or somehting like that. So you can plug it in with or without using IIS.

**Comment by mgdagpin** [comment] 2022-08-23 06:35
> I am working on a web api for the Scheduler. This will be only support net core. The first release will only contain scheduler functions but i will continue to cover jobs,triggers and calendars. It is based on that you have one server with possibility for multiple schedulers on the same server.
> 
> Im also working on a realtime dashboard for the scheduler but there are no plans currently to release this as open source. ![SchedulerDashboard](https://user-images.githubusercontent.com/45846979/64149249-b9edec00-ce25-11e9-8497-489acdfb74bc.png) ![SchedulerOverView](https://user-images.githubusercontent.com/45846979/64149262-c1ad9080-ce25-11e9-8ebf-2282904315da.png)

Do we have news on this? happy to help!

**Comment by Sicos1977** [comment] 2022-11-09 06:05
Fine by me, only to bad it can't be used on a lower framework like .net 4.8. It would be nice if that was also possible so that we can get rid of the .net remoting.

**Comment by lahma** [comment] 2022-11-09 07:39
I did consider the full framework issue. Basically HTTP API still allows you to manage scheduler remotely from full framework application. Might be easier to convert server-side scheduler to modern .NET while keeping WinForms app in maintenance mode for example.

**Comment by adurmus** [comment] 2022-11-09 10:06
Is there an example with `Worker`?  Worker(Window Service) will run the jobs and all endpoints will be there.  And a web application will check/run/schedule jobs through those endpoints?

**Comment by upCASE** [comment] 2023-05-25 12:11
This feature looks really nice and I would love to see this in the next release.
Having a HTTP API  would enable me to do some basic dashboarding in my Blazor WASM frontend without having to reinvent the wheel...
Is there some update about this?

**Comment by jafin** [comment] 2023-05-25 23:01
@upCASE  there was a HTTP API that was added in a while ago, take a look https://github.com/quartznet/quartznet/pull/1803

**Comment by upCASE** [comment] 2023-05-26 05:48
@jafin Thanks for your reply.
I know the PR, had a look at the code and then found this issue referencing it. My question is more related to when this will be "officially" released. In the latest release 3.6.2 it's not included apparently and I was wondering if it will be in the next one, or if it will be postponed to some later release.

**Comment by panagiotiskompis** [comment] 2023-09-21 15:26
Any news regarding the release of the quartz HTTP API? Is there an estimated release date?

**Comment by alanblack** [comment] 2023-11-02 10:47
I am also interested in including the HttpApi in the 3.x branch. Is this planned?
Merged and adjust the PR by own to the best of my ability and it seems to work at first glance.

**Comment by Sicos1977** [comment] 2023-11-02 11:37
If you are in a hurry. I also started building an HTTP API but never finished it because #1803 beat me and finished first. But maybe you are in luck and I have covered the things you need. It should work with the 3.x version.

https://github.com/Sicos1977/QuartzWebApi

**Closed** 2024-06-25 09:44 UTC
