### ISSUE TITLE
Invalid attempt to read a prior column using SequentialAccess

### ISSUE THREAD

**Issue by pccai** [quartznet/quartznet#2400] opened 2024-06-13 06:13 UTC
**Describe the bug**

Quartz|xyz|Quartz.JobPersistenceException: Couldn't retrieve job: 6097,Invalid attempt to read a prior column using SequentialAccess
 ---> Dm.DmException (0x80004005): 6097,Invalid attempt to read a prior column using SequentialAccess
   at Dm.DmError.ThrowDmException(Int32 code)
   at Dm.DmDataReader.IsDBNull(Int32 i)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.ReadBytesFromBlob(IDataReader dr, Int32 colIndex, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.GetObjectFromBlob[T](DbDataReader rs, Int32 colIndex, CancellationToken cancellationToken)

**Version used**

With which version did you encounter this behavior.

**To Reproduce**

Ideally code samples or event unit test.

**Expected behavior**

**Additional context**

**Comment by jafin** [comment] 2024-06-13 06:25
Hi @pccai ,

What version of Quartz?
What version of SQL
If possible any reproduceable code sample?

**Comment by lahma** [comment] 2024-06-13 06:37
Looks like a very unsupported scenario, (`DmDataReader`).

**Comment by pccai** [comment] 2024-06-13 08:48
my action:
using var rs = await cmd.ExecuteReaderAsync(System.Data.CommandBehavior.Default, cancellationToken).ConfigureAwait(false);
......
override and change CommandBehavior to Default, then it works for me.

**Comment by pccai** [comment] 2024-06-13 08:49
> Hi @pccai ,
> 
> What version of Quartz? What version of SQL If possible any reproduceable code sample?

3.8.1/net8

**Comment by lahma** [comment] 2024-06-26 07:01
Closing as cannot reproduce as using some custom libraries.

**Closed by lahma** 2024-06-26 07:01 UTC
