### ISSUE TITLE
There is no metadata information for provider 'MySql-50'

### ISSUE THREAD

**Issue by 001saraju** [quartznet/quartznet#483] opened 2017-05-15 11:36 UTC
I am using .net core v 1.1.0 and facing issue with Quartz v 3.0.0-alpha2

I want to store job data in mysql database,

I am passing below properties for StdSchedulerFactory

            NameValueCollection properties = new NameValueCollection
            {
                ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                ["quartz.serializer.type"] = "json", 
                ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz",
                ["quartz.jobStore.tablePrefix"] = "QRTZ_",
                ["quartz.jobStore.dataSource"] = "myDS",
                ["quartz.dataSource.myDS.connectionString"] = "Server=localhost;Port=3306;Database=QuartzDB;uid=root;password=1234;",
                ["quartz.dataSource.myDS.provider"] = "MySql-50",
                ["quartz.jobStore.useProperties"] = "true" 
            };

while I am fire dotnet run command it throws an error like,

Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not Initialize DataSource: myDS) ---> Quartz.SchedulerException: Could not Initialize DataSourc
e: myDS ---> System.ArgumentOutOfRangeException: There is no metadata information for provider 'MySql-50'
Parameter name: providerName

Is there I missed or anyone to help me for the same ?

Thanks in advance

**Comment by lahma** [comment] 2017-07-24 07:59
duplicate of #493 , so support will be in alpha3, provider will be just "MySql" that binds to version available.

**Closed by lahma** 2017-07-24 07:59 UTC
