### ISSUE TITLE
Scheduler cannot recover from database connection error

### ISSUE THREAD

**Issue by Chralex** [quartznet/quartznet#740] opened 2019-03-22 15:45 UTC
### Expected behavior

If a job is scheduled using a simple repeating trigger then a temporary loss of a database connection should be recoverable.

### Actual behavior

Jobs scheduled on that scheduler does never recover and start working normally again.

### Steps to reproduce

1. Setup a database and configure the quartz standard scheduler factory to use it. In my example I'm using PostgreSQL.
2. Create a scheduler and schedule a job with a simple trigger that runs every 10 seconds.
3. While you know that the job is not executing, restart the PostgreSQL database service.
4. See that the job configured with a simple trigger that should run every ten seconds no longer runs, even if you wait for 5 minutes. 

The example uses .NET Core 2.2, NpgSQL 4.0.7 and Quartz 3.0.7
```csharp
using Quartz;
using Quartz.Impl;
using System;
using System.IO;
using System.Threading.Tasks;

namespace QuartzConnectionLossExample
{
	class Program
	{
		// Please don't target this against a database that you are using for other stuff.
		private static readonly string _connectionString = "Host=localhost;Port=5432;Database=quartztest;UserName=postgres;Password=postgres";

		/// <summary>
		/// Path to the script that sets up quartz database tables. Set to null if you don't want to clear the public schema and create quartz database objects.
		/// </summary>
		private static readonly string _quartzSQLScriptPath = "Sql/quartzSetupScript.sql";
		private static readonly bool dontSetup = false;

		private static readonly System.Collections.Specialized.NameValueCollection quartzConfig =
			new System.Collections.Specialized.NameValueCollection()
			{
				{ "quartz.serializer.type", "json" },
				{ "quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
				{ "quartz.jobStore.driverDelegateType"," Quartz.Impl.AdoJobStore.PostgreSQLDelegate, Quartz" },
				{ "quartz.jobStore.tablePrefix", "QRTZ_" },
				{ "quartz.jobStore.dataSource", "PostgreSql" },
				{ "quartz.dataSource.PostgreSql.connectionString", _connectionString },
				{ "quartz.dataSource.PostgreSql.provider", "Npgsql" },
				{ "quartz.plugin.triggHistory.type", "Quartz.Plugin.History.LoggingJobHistoryPlugin, Quartz.Plugins" },
				{  "quartz.threadPool.threadCount", "2" }
			};

		private static readonly StdSchedulerFactory _schedulerFactory = new StdSchedulerFactory(quartzConfig);

		static void Main(string[] args)
		{
			Console.WriteLine("Example start.");

			if (!dontSetup)
			{
				SetupDatabase();
			}

			var scheduler = _schedulerFactory.GetScheduler().GetAwaiter().GetResult();

			SetupJobAndSimpleTrigger(scheduler);

			Console.WriteLine("Scheduler started, feel free to restart your database service and see if it can recover from that.");
			Console.ReadLine();
		}

		private static void SetupJobAndSimpleTrigger(IScheduler scheduler)
		{
			IJobDetail job = null;

			if (!scheduler.CheckExists(new JobKey("TestJob", "TestGroup")).GetAwaiter().GetResult())
			{
				job = JobBuilder.Create<TestJob>()
					.WithIdentity(new JobKey("TestJob", "TestGroup"))
					.WithDescription("Test.")
					.RequestRecovery(true)
					.StoreDurably(true)
					.Build();
			}
			else
			{
				job = scheduler.GetJobDetail(new JobKey("TestJob", "TestGroup")).GetAwaiter().GetResult();
			}

			if (!scheduler.CheckExists(new TriggerKey("TestTrigger", "TestGroup")).GetAwaiter().GetResult() && job != null)
			{
				var trigger = TriggerBuilder.Create()
					.WithIdentity(new TriggerKey("TestTrigger", "TestGroup"))
					.WithDescription("Runs every 10 seconds")
					.WithSimpleSchedule(x => x
						.WithIntervalInSeconds(10)
						.RepeatForever()
						.WithMisfireHandlingInstructionIgnoreMisfires()
					)
					.StartNow()
					.EndAt(null)
					.Build();

				scheduler.ScheduleJob(job, trigger).GetAwaiter().GetResult();
			}

			scheduler.Start().GetAwaiter().GetResult();
		}

		static void SetupDatabase()
		{
			#region Clean public schema and setup quartz database objects.
			if (!string.IsNullOrWhiteSpace(_quartzSQLScriptPath))
			{
				Console.WriteLine("Setting up database");

				using (var connection = new Npgsql.NpgsqlConnection(_connectionString))
				{
					connection.Open();

					using (var command = connection.CreateCommand())
					{
						command.CommandText =
$@"
DROP SCHEMA ""public"" CASCADE;
CREATE SCHEMA ""public"";
" + File.ReadAllText(_quartzSQLScriptPath);

						using (var transaction = connection.BeginTransaction())
						{
							command.Transaction = transaction;
							command.ExecuteNonQuery();
							transaction.Commit();
						}
					}
				}

				Console.WriteLine("Database setup completed");
			}
			else
			{
				Console.WriteLine("No setup script specified, setup skipped.");
			}
			#endregion
		}
	}

	// Once you hit the breakpoint below you should hit continue immediately, and then immediately try to restart the database.
	// Basically it will only fail if the database connection error occurs before the Execute method is called.
	[DisallowConcurrentExecution]
	public class TestJob : IJob
	{
		public Task Execute(IJobExecutionContext context)
		{
			System.Diagnostics.Debugger.Break();
			return Task.Delay(1000);
		}
	}
}
```

**Comment by Chralex** [comment] 2019-03-26 11:36
I noticed that there is actually something wrong in the example provided, so I will close this for now and open it again later once I can make an example that can make it fail reliably. Basically what happens on our production system is that if the db connection is closed forcibly for whatever reason that might be, an exception always seem to occur in the StdAdoDelegate.SelectTriggersInState method, and it never seems to recover from that.

The issue in my example is that I forgot to await or make it get the result of the IScheduler.Start, when doing that it seems that it actually gets the exception elsewhere and from there it is recoverable.

**Comment by Chralex** [comment] 2019-03-27 13:11
I have updated the example, and changed the instructions for reproduction, So I will reopen this issue.

**Comment by SeanFarrow** [comment] 2019-08-15 15:15
Are there any logs available for the case when an exception is thrown due to a disconnection?

**Comment by Chralex** [comment] 2019-08-23 14:32
Unfortunately I do not have the original log for when it happened, since it happened a while ago.
But what I've saved an excerpt of the log on the web server when the error occurred in our bug tracking system, which looks like this:

`2019-03-21 17:57:37.593 +00:00 [Error] Caught job persistence exception: Couldn't select trigger state: Exception while writing to stream
2019-03-21 17:57:37.596 +00:00 [Error] Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected
System.InvalidOperationException: Transaction not connected, or was disconnected
at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError)`

I've added logging to the example above and when I reproduce it I get the following log:
[quartz not recovering log.txt](https://github.com/quartznet/quartznet/files/3534946/quartz.not.recovering.log.txt)

I also notice now that it actually says I am using 3.0.8 as opposed to 3.0.7 as I wrote. I guess it was 3.0.7 on the production system at the time and 3.0.8 in the example.

**Comment by SeanFarrow** [comment] 2019-08-23 14:45
Hi,

Thanks, I don't have docker or postgres on this machine currently, but If I can get a docker environment installed in the next few weeks, I'll have a look at this.

I am moving house though, so it may take a bit longer.

One other thought, have you tried to reproduce the problem with other database drivers such as SqlServer and MySql?

**Comment by Chralex** [comment] 2019-08-23 14:53
I have not tried with other database drivers.

**Comment by SeanFarrow** [comment] 2019-08-23 15:03
Is this something you would be able and willing to do in the next few weeks or so?
I'd like to get a feel as to whether the problem is localised to PostGres.

**Comment by Chralex** [comment] 2019-08-23 16:43
Using SqlServer instead seems to work fine.

**Comment by SeanFarrow** [comment] 2019-08-23 17:07
Ok, if you are running vs2019, do you have the time either next week or the week after for a live share session?

**Comment by Chralex** [comment] 2019-08-23 17:20
Sure, I am available from 11 AM CET to 7 PM CET.

I don't know where you want to discuss the exact time and so on. One thing you can do is join our discord server if you have discord: https://discordapp.com/invite/lastoasis then find me there and message me, you probably need to add me as a friend first.

**Comment by SeanFarrow** [comment] 2019-08-23 17:38
Hi,

I don't have discord, feel free to ping me an Email:
sean.farrow@seanfarrow.co.uk

That's definitely easiest.

**Comment by Chralex** [comment] 2019-08-26 10:22
I've sent you an e-mail, just letting you know here in case it ends up in spam.

**Comment by SeanFarrow** [comment] 2019-08-26 15:37
Having discussed this with @Chralex  earlier today, it appears that the NPGSQL driver does not perform retries.
@lahma, it is my view that, given every other driver seems to retry, we need to ideally build something in for the PostGres folks.

Having overridden everything in the StdAdoDelegate for @Chralex, given there time constraints, I think we could have a set of Execute functions passing through the function on the SQL command we wish to call. The base implementation would just call this function with any databases/persistence technologies that do not provide retries overriding these functions to do this as required.

Does this sound like something that would be acceptable?

**Comment by lahma** [comment] 2019-08-26 16:07
Thank you for digging into this 👍🏻. Sounds like the transient error handling should support per-delegate detection and we should figure out the common recoverable errors with Postgres and how to detect them. I don't know if npsgl folks are considering to implement same kind of retry that MS driver supports.

**Comment by SeanFarrow** [comment] 2019-08-26 16:59
It doesn’t seem that they are.

I don’t think we need to worry about delegate detection, as we are dealing with a case where nothing at all gets brought back from the db, no matter how long you leave it, so retrying is the only option.

It looks like I’ll manage to do this by adding at most 5 virtual functions to the standard delegate.

**Comment by SeanFarrow** [comment] 2019-08-26 21:51
@lahma,

I've just finished a first draft of this, for everything other than classes deriving from ITriggerPersistenceDelegate.

Before I look at the ITriggerPersistenceDelegate specifically, I have a query regarding how to detect transient exceptions from PostGres, given we can't take a dependency on the NpgSql driver.

I'm thinking we either do this by relying on the string name, which I know is hacky, or, we look at splitting the database delegates in to there own assemblies.

Do you have any thoughts or other ideas?

**Comment by StefanHaug** [comment] 2019-12-10 13:49
I'm having this issue also, using MS SQL. 

2019-12-06 13:18:50,276 [91] ERROR Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder (null)  Staging - Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected
System.InvalidOperationException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError)

**Comment by Squall90** [comment] 2019-12-10 20:25
I am having the exact same issue with MS SQL. 
 ERROR Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder (null) Staging - Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected
System.InvalidOperationException: Transaction not connected, or was disconnected
at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError)

Is there a workaround?
The issues is that ALL of the jobs are halted until the service is restarted.

**Comment by Cynicszm** [comment] 2020-04-18 09:35
Same error using SQL Server and ALL jobs stop until service restart, any views on a fix / workaround ?

**Comment by SeanFarrow** [comment] 2020-04-18 11:23
Hi,

Is three an exception thrown by the JobStore implementation before you see the problem?
Also, could this be duplicated by LocalDb?
If you can produce a repository that reproduces this, I’d be happy to have a look.

Thanks,
Sean.

**Comment by Cynicszm** [comment] 2020-04-18 11:35
The only exception in the log is:

[Error] Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected
System.InvalidOperationException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError)

Unfortunately I can't reproduce it, occurred twice in 7 days at different times. 

I'm currently testing after increasing the CommandTimeout to see if it helps (similar to https://stackoverflow.com/questions/45503928/quartz-net-sql-server-jobs-stuck-as-blocked)

I'll try increasing the log level and see if I get some more useful info.

**Comment by lahma** [comment] 2020-07-13 13:59
This was probably fixed with https://github.com/quartznet/quartznet/pull/879 so upcoming beta 2 / dev feed builds should be used. We can reopen if still an issue.

**Closed by lahma** 2020-07-13 13:59 UTC

**Comment by lahma** [comment] 2020-07-14 18:47
[3.1 beta 2](https://www.quartz-scheduler.net/2020/07/14/quartznet-3-1-beta-2-released/) has been released and hoping this will be also fixed by it.

**Comment by nikriaz** [comment] 2023-12-07 20:27
I use Quartz 3.6.2 for retrying critical transactions in case of misbehavior of third-party API.
It worked well in tests but when actual disaster occured I've got the bunch of exactly the same errors in log:

```
|ERROR|Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder|Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected System.InvalidOperationException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError) 
```
Obviously, my SQL was in high load because of disaster but not critically high. All other parts of app worked well but Quartz, that was the only subsystem affected. I think, there is something wrong with SQL communication. The good news, despite of all these errors, finally all tasks were completed. But it looks alarming and very difficult to debug or identify what was caused my own bugs, and what by Quartz.

**Comment by SeanFarrow** [comment] 2023-12-07 22:37
Hi Nikolay,

Whilst I don’t know what the cause of the problem is, I wonder whether using OpenTelemetry will help here?

Some other questions:
Is the Quartz data in the same database as everything else? Does moving this to another database help?
What is your hosting setup—are you in the cloud?
Without quartz, how much load is on the database in normal operation?

Thanks,
Sean.

**Comment by nikriaz** [comment] 2023-12-07 22:50
@SeanFarrow 
- Quartz is on the separate db but on the same MS SQL instance as some few other dbs
- This is cluster of 2 local servers. SQL is on AGs (Always On Availability Groups)
- I never looked how heavily Quartz relies on db connection but at a rough guess my normal load is much higher than I would expect from Quartz on that incident. Meaning 300 transactions per few seconds as it was with Quartz during disaster is pretty normal.

**Comment by SeanFarrow** [comment] 2023-12-07 23:22
Which SQLClient implementation are you using System.Data.SQLClient, or Microsoft.Data.SQLClient?
