### ISSUE TITLE
Quartz tries to access disposed logger after the host has been restarted

### ISSUE THREAD

**Issue by manuelelucchi** [quartznet/quartznet#1781] opened 2022-10-07 14:48 UTC
**Describe the bug**

For architectural reasons of my aspnetcore project, the host building and execution is in a for loop, since you can restart the server from the client, something like this

```csharp

async Task LoadAsync()
{
	var builder = WebApplication.CreateBuilder(args);
        // Configuration
        builder.Services.AddQuartz(b =>
	{
		b.SchedulerId = "1";
		b.SchedulerName = "EAE";
		b.UseMicrosoftDependencyInjectionJobFactory();
	});

	builder.Services.AddQuartzServer(options =>
	{
		options.WaitForJobsToComplete = true;
	});

        var app = builder.Build();
        // Configuration
        app.Run();
}

while (true)
{
	await LoadAsync();
}

```

The first run, there are no problems. But when I force the WebApplicationHost to stop using `IHostApplicationLifetime.StopApplication()`, while everything restarts correctly, Quartz crashes with this error

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Quartz.Simpl.MicrosoftLoggingProvider.GetLogger(String name)
   at Quartz.Logging.LogProvider.GetLogger(String name)
   at Quartz.Xml.XMLSchedulingDataProcessor..ctor(ITypeLoadHelper typeLoadHelper)
   at Quartz.ContainerConfigurationProcessor..ctor(ITypeLoadHelper typeLoadHelper, IOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
```

It seems like Quartz caches globally the injected Microsoft Logger, so when the host is stopped and the logger is disposed, the same reference remains

**Version used**
3.5.0

**To Reproduce**

A code like the one I showed before with some event that calls `IHostApplicationLifetime.StopApplication()`

**Expected behavior**

It should not raise that error

**Comment by lahma** [comment] 2022-10-07 14:53
OK this is quite the corner case... Can you come up with some PR proposal to fix the issue against 3.x branch?

**Comment by manuelelucchi** [comment] 2022-10-11 09:50
I'll dig it up and let you know if I'm able to

**Comment by manuelelucchi** [comment] 2022-10-13 11:50
I can't come up with a PR yet, but it seems that `SetLoggerFactory` in `ServiceCollectionQuartzConfigurator` is never called automatically (the same goes for the underlying `SetLogProvider`) so i'm not sure how the logging is working in the first place without specifing anything

**Comment by aheubusch** [comment] 2022-10-18 06:31
I have come across a very similar problem today. I have two tests that create and dispose a host. In addition I have a custom logger that throws after it gets disposed. The second test fails because `DBConnectionManager`, which is a singleton, holds the logger instance from the first test. When it logs in the second test the custom logger throws `ObjectDisposedException`.
https://github.com/quartznet/quartznet/blob/ab72bf7838accd208612bd2f0333c904a9d2602b/src/Quartz/Util/DBConnectionManager.cs#L40-L59
3.x and 4.x are affected.

**Comment by lahma** [comment] 2022-10-19 03:22
I think @aheubusch has a different case of dispose. The original shows logger factory being disposed but in `DBConnectionManager` case it's `ILogger`, which is kind of weird as I would assume they are non-disposable.

**Comment by aheubusch** [comment] 2022-10-19 07:45
@lahma Indeed my case is different but I believe both are caused by the same underlying problem. Quartz uses singleton which are then used across multiple hosts.
You are correct that `ILogger` are usually non-disposable. I have a custom ILogger/ILoggerProvider which do get disposed.

**Comment by manuelelucchi** [comment] 2022-11-14 14:53
Any news on this @lahma? I'm not able to investigate further at the moment

**Comment by lahma** [comment] 2022-11-14 14:57
No news.

**Comment by manuelelucchi** [comment] 2022-11-28 14:48
@aheubusch I found a workaround that seems to work. 
```csharp
Quartz.Logging.LogProvider.SetCurrentLogProvider(null);
services.AddQuartz(b => ...)
```

**Comment by lahma** [comment] 2022-12-25 09:57
@manuelelucchi  Can you try the latest  3.5.1 preview from MyGet feed? Quartz was using `IApplicationLifetime` instead of `IHostApplicationLifetime` so the call to stop might not have reached Quartz the expected way.

**Comment by admirajutta** [comment] 2023-02-06 13:36
@lahma The issue is still there with version 3.6.0.
`Quartz.Logging.LogProvider.SetCurrentLogProvider(null);` works as an workaround, as mentioned by @manuelelucchi

**Comment by lahma** [comment] 2023-02-06 13:38
Someone want to propose a PR with desired fix?

**Comment by jafin** [comment] 2023-02-13 05:46
Apologies if I have not completely understood the issue.
I tried to write an app that attempts to do what the issue above describes.
See https://github.com/jafin/quartznet/tree/demo/app-restart
Start the Quartz.Examples.AppRestart app there is an endpoint /app/  to restart thee program.

From what I see, the app shuts down, is restarted and the logger continues to work.
![image](https://user-images.githubusercontent.com/127927/218380089-057198d1-d97f-45bf-b95d-f12a160044cb.png)

Perhaps I've missed something?  You do mention the LoggFactory being auto created somehow rather that wired up in AppStart. Perhaps that is it?

**Comment by joolify** [comment] 2023-04-24 09:00
This issue disappeared when I changed to `CreateDefaultBuilder` and `UseWindowsService` from `CreateBuilder` of `WebApplication`.

```
var builder = Host.CreateDefaultBuilder(args).UseWindowsService();

builder.Services.AddQuartz(b =>
{
	b.SchedulerId = "1";
	b.SchedulerName = "EAE";
	b.UseMicrosoftDependencyInjectionJobFactory();
});

builder.Services.AddQuartzServer(options =>
{
	options.WaitForJobsToComplete = true;
});

var app = builder.Build();
// Configuration
app.Run();
```

**Comment by A9G-Data-Droid** [comment] 2023-09-18 16:48
I was also seeing this in unit testing due to rapid calls to:

```c#
IScheduler scheduler = await SchedulerBuilder.Create("Test", "Scheduler")
    .UseDefaultThreadPool(options => options.MaxConcurrency = 1)
    .UseInMemoryStore()
    .BuildScheduler();
```

I am not even running the tests in parallel and yet some sort of race condition exists. 

Luckily, `Quartz.Logging.LogProvider.SetCurrentLogProvider(null);` is viable in testing but this would be a problem if I cared about the contents of the Quartz log.

**Comment by daveidmx** [comment] 2024-01-29 02:30
I'm running into this with integration tests of my aspnetcore application. Each test case necessarily creates and disposes its own `WebApplicationFactory`. The first test case runs fine; the second test case throws the exception as reported:
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
```

Please let me know if I can provide any information to help resolve this!

**Comment by lahma** [comment] 2024-08-03 09:59
Closing this as version 3.12 contains fixes related to this. Anyone is welcome to submit further PRs if there are still problems.

**Closed by lahma** 2024-08-03 09:59 UTC

**Comment by rpallares** [comment] 2025-11-03 10:04
> Closing this as version 3.12 contains fixes related to this. Anyone is welcome to submit further PRs if there are still problems.

Hi,

I use the version 3.15.1 and I encounter the issue in my testing environment.
Thankfully the workarounds are working but I need to apply it:
```cs
Quartz.Logging.LogContext.SetCurrentLogProvider(NullLoggerFactory.Instance);
```
