### ISSUE TITLE
Some dates missing when computing them over DST period using CronScheduler

### ISSUE THREAD

**Issue by thegrima** [quartznet/quartznet#539] opened 2017-11-03 15:19 UTC
### Version

Version: 2.6.1

### Expected behavior

Using the provided code below, i'm trying to generate all dates of a cron expression between two dates around the daylight saving of this fall (2017-10-29) in the western europe timezone. Used cron expression is **"0 0/15 * * * ?"** which i intend to mean "every 1/4h".

Unless i miss something, generated dates should be :

> 29-10-17 00:00:00 +00:00
> 29-10-17 00:15:00 +00:00
> 29-10-17 00:30:00 +00:00
> 29-10-17 00:45:00 +00:00
> **29-10-17 01:00:00 +00:00**
> **29-10-17 01:15:00 +00:00**
> **29-10-17 01:30:00 +00:00**
> **29-10-17 01:45:00 +00:00**
> 29-10-17 02:00:00 +00:00
> 29-10-17 02:15:00 +00:00
> 29-10-17 02:30:00 +00:00
> 29-10-17 02:45:00 +00:00
> 29-10-17 03:00:00 +00:00

### Actual behavior

Generated dates are :

> 29-10-17 00:00:00 +00:00
> 29-10-17 00:15:00 +00:00
> 29-10-17 00:30:00 +00:00
> 29-10-17 00:45:00 +00:00
> 29-10-17 02:00:00 +00:00
> 29-10-17 02:15:00 +00:00
> 29-10-17 02:30:00 +00:00
> 29-10-17 02:45:00 +00:00
> 29-10-17 03:00:00 +00:00

It almost looks like CronExpression was confusing spring-ahead and fall-behind behavior.

### Steps to reproduce

```csharp
            var tzi = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");
            var begin = new DateTime(2017, 10, 29, 00, 00, 00, DateTimeKind.Utc);
            var end = new DateTime(2017, 10, 29, 03, 00, 00, DateTimeKind.Utc);

            var triggerBuilder = TriggerBuilder.Create();

            var schedulerBuilder = CronScheduleBuilder
                    .CronSchedule("0 0/15 * * * ?")
                    .InTimeZone(tzi);

            var trigger = triggerBuilder
                    .WithSchedule(schedulerBuilder)
                    .Build() as IOperableTrigger;

            var dates = TriggerUtils.ComputeFireTimesBetween(trigger, null,
                new DateTimeOffset(begin),
                new DateTimeOffset(end));

            foreach (var d in dates)
            {
                Console.WriteLine(d);
            }

            Console.ReadKey();
```

**Comment by lahma** [comment] 2017-11-04 10:36
The problem is that UTC and local date mapping is ambiguous at that time.

If you change your code to print local times:

    foreach (var d in dates)
    {
         Console.WriteLine(TimeZoneInfo.ConvertTimeFromUtc(d.DateTime, tzi));
    }

The output is:

> 29.10.2017 2.00.00
> 29.10.2017 2.15.00
> 29.10.2017 2.30.00
> 29.10.2017 2.45.00
> 29.10.2017 3.00.00
> 29.10.2017 3.15.00
> 29.10.2017 3.30.00
> 29.10.2017 3.45.00
> 29.10.2017 4.00.00

**Comment by thegrima** [comment] 2017-11-06 10:40
One hour of time is still missing. 

The interval (in local time) : 
> 29-10-17 02:00:00
> 29-10-17 02:15:00
> 29-10-17 02:30:00
> 29-10-17 02:45:00

should be happening twice on that night.

To try to explain better, I think the expected generated dates in local time should be :
> 29-10-17 01:00:00 +02:00
> 29-10-17 01:15:00 +02:00
> 29-10-17 01:30:00 +02:00
> 29-10-17 01:45:00 +02:00
> 29-10-17 02:00:00 +02:00
> 29-10-17 02:15:00 +02:00
> 29-10-17 02:30:00 +02:00
> 29-10-17 02:45:00 +02:00
> 29-10-17 02:00:00 +01:00
> 29-10-17 02:15:00 +01:00
> 29-10-17 02:30:00 +01:00
> 29-10-17 02:45:00 +01:00
> 29-10-17 03:00:00 +01:00

**Comment by lahma** [comment] 2017-11-06 11:40
The fall behavior was changed to run the standard time occurrence, see details here: https://github.com/quartznet/quartznet/pull/317

**Comment by ackphht** [comment] 2017-11-06 22:49
I don't think this behavior is correct either. This just bit us here in the U.S. this past weekend when our DST ended. We have a cron schedule set to run every half hour ("0 0/30 * * * ?") and when the time changed on Saturday night/Sunday morning, it completely skipped an hour, like this:

2017-11-05 00:00:00 -05:00
2017-11-05 00:30:00 -05:00
2017-11-05 01:00:00 -05:00
2017-11-05 01:30:00 -05:00
2017-11-05 02:00:00 -06:00
2017-11-05 02:30:00 -06:00
2017-11-05 03:00:00 -06:00

there should also have been entries for "01:00:00 -**06**:00" and "01:30:00 -**06**:00"

I would think for a cron schedule that just says run every X hours/minutes/seconds, it shouldn't really matter if it's an ambiguous time or not because the actual current time doesn't matter for that kind of schedule.

**Comment by lahma** [comment] 2017-11-07 05:55
If you look at the [FAQ section about triggers and DST](https://www.quartz-scheduler.net/documentation/faq.html#daylight-saving-time-and-triggers) of the documentation, it should reflect with how things work presently.

I do understand that when we are talking about DST there's always another way to handle things. Ideally we would never schedule anything to happen in that DST window, especially with cron-based scheduling.

When DST occurs to get consistent "every fifteen minutes", use simple trigger. For "at 2 am when computer clocks says it's that time and please don't send payments twice that night", use cron. Simple trigger is easy to setup as start at even hour and run every fifteen minutes. Cron on the other hand is classically used for "these weekdays and at this hour" kind of scenarios to oversimplify.

Confusion and disappointment is bound to happen when there are two ways to do recurring scheduling on hour level with triggers that have different semantics. And then there was this person who invented that we need DST.

**Comment by ackphht** [comment] 2017-11-07 16:31
I think it would be helpful to make that behavior of the cron triggers more prominent, because that is not the behavior that I, at least, would expect. I would not expect the library to be making that decision for my application. To me, the triggers should just fire whenever they're configured to fire and the application should decide how to handle those ambiguous DST times in the most appropriate way for the app. I put a lot of effort into making sure our application would work correctly during the DST rollovers only to have it still fail because the triggers never fired in the first place.

And with that, I will stop arguing now :).

**Comment by lahma** [comment] 2017-11-07 16:47
@ackphht I hope we cannot call this arguing here, just conversation about a complex topic. I feel we can close this ticket as "works as documented", even though it can be counter-intuitive for some cases and even non-satisfactory for everyone.

I welcome pull requests that are backwards compatible and offer help in form of warnings or whatever could help with understanding the behavior that will come into effect by choosing specific trigger and schedule combination.

As a small child's father and as a scheduling library author, I do sincerely hope that we could rid ourselves from all of this DST nonsense that messes our sleep, rhythm and code.

**Closed by lahma** 2017-11-07 16:47 UTC
