### ISSUE TITLE
MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT missing

### ISSUE THREAD

**Issue by pantonis** [quartznet/quartznet#1020] opened 2020-11-03 09:36 UTC
**Is your feature request related to a problem? Please describe.**
My job class has DisallowConcurrentExecution attribute to avoid concurrence, so the same job just can run once per time (OK)
It is a CRON and runs every 1 minute (OK)
The time is 13:01 and the the job starts run (OK)
Now the time is 13:02 and the previous job didn't finish yet (OK)
As the class is annotated the next job will not start (IT IS GREAT - OK)
Now the time is 13:02:15 and the first job just finished (OK)
The next job which was supposed to start at 13:02 fires at 13:02:15 (NOT OK)
I would like this job not to run but the next job at 13:03 to run.
After reading I found that in java you can do this by marking the job with ```MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT``` link [here](http://www.quartz-scheduler.org/api/2.1.7/org/quartz/SimpleTrigger.html)
I found out that this is not supported in quartz.net (maybe I am wrong)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lahma** [comment] 2020-11-03 16:36
Duplicate of #1021

**Closed by lahma** 2020-11-03 16:36 UTC

**Comment by pantonis** [comment] 2020-11-03 17:35
Sorry when I posted #1020 it I got 404 and I reposted it.
