### ISSUE TITLE
Concurrent jobs are fired sometimes

### ISSUE THREAD

**Issue by leotsarev** [quartznet/quartznet#703] opened 2018-11-01 14:09 UTC
### Actual behavior
Sometimes our cluster starts one job in parallel. They are DisallowConcurrentExecution, and in 99.9% cases that's are working, but _sometimes_ everything goes nuts.

Our system time is not stable, and our sysops explicitly not guarantee time sync between machines. Could it be related? How we can approve or disprove this?
### Steps to reproduce

                    ["quartz.scheduler.instanceName"] = config.SchedulerName,
                    ["quartz.scheduler.instanceId"] = "AUTO",
                    ["quartz.jobStore.clustered"] = "true",

                    ["quartz.threadPool.threadCount"] = "20",
                    ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                    ["quartz.jobStore.useProperties"] = "true",
                    ["quartz.jobStore.dataSource"] = "myDS",
                    ["quartz.dataSource.myDS.connectionString"] = config.ConnectionString,
                    ["quartz.dataSource.myDS.provider"] = "SqlServer-20",

                    // if running MS SQL Server we need this
                    ["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz"

**Comment by alexorekhov** [comment] 2018-12-11 13:12
@lahma Sorry if I bother you, but could you please take a look on this issue. We face it with our cluster too. I hoped that it had been resolved in 3.0.7, but, unfortunately, it's not. 
If it possible for you, please, pay your attention to the @AnSmol question.
Thanks in advance.

**Comment by alexorekhov** [comment] 2018-12-28 08:41
@lahma, thank you for your response. Could you please provide me a little beat more information about time-sync. What is a permissible discrepancy between hosts in a cluster? 
We use NTP, is that enough?

**Comment by lahma** [comment] 2018-12-28 08:57
@alexorekhov NTP should suffice, we are talking something more than a second being bad. With NTP you reach something like nano/milliseconds precision I guess. The queries are made relative to DateTime.UtcNow so if that differs between machines confusion ensues.

**Comment by alexorekhov** [comment] 2018-12-28 09:11
@lahma According to [MS Documentation](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/support-boundary) 1-second accuracy is available only in Windows server OS starting on 2016. 
It said:

> Earlier versions of Windows (Prior to Windows 10 1607 or Windows Server 2016 1607) cannot guarantee highly accurate time.

We are using  Windows 2012 R2 now, so I wonder, do we have to update our cluster to Windows 2016 to get Quartz working properly? Also, could you please provide a little more details about "confusion ensues" that we will face in case we 1-second accuracy is not an option?

**Comment by lahma** [comment] 2018-12-28 10:01
One second is not a hard requirement, a rule of thumb. But generally the servers should "show the same second on the clock". When there's considerable amount of difference between clocks different kind of things can happen. For example one node can consider you trigger misfired if it has it's clock set to earlier point in time than the one that the scheduled the trigger (here job store configuration plays a part too with its threshold configuration).

You have checked the other configuration already (SQL Server delegate, lock handler) and now only thing that is left the time difference (or other bug) to explain the behaviour you are seeing? You haven't yet told anythng about your setup except that you are running Windows 2012 R2.

It's enough to have one scheduler not configured properly like clustered=false and others as true and the cluster will be broken.

You can also always enable debug/info logging if you problem is easily reproducible and see what Quartz thinks is happening.

**Comment by leotsarev** [comment] 2018-12-28 11:59
```
quartz.scheduler.instanceName = 'ERP'
quartz.scheduler.instanceId = "AUTO"
quartz.jobStore.clustered = "TRUE"
quartz.threadPool.threadCount = 10
quartz.jobStore.type = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
quartz.jobStore.useProperties = "true",
quartz.jobStore.dataSource = "myDS",
quartz.dataSource.myDS.connectionString = <hidden>,
quartz.dataSource.myDS.provider"= "SqlServer",
quartz.serializer.type = "binary"
quartz.jobStore.lockHandler.type = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz"
```

**Comment by lahma** [comment] 2018-12-28 12:05
@leotsarev 

add missing:

`properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz";`

remove:

`quartz.jobStore.lockHandler.type = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz"`

This configuration seems to be for 3.x unlike the original issue. Ensure all nodes have similar configuration. Add logging if possible to catch the event which shows wrong behaviour. Quartz should have already warned you about the lock handler configuration.

**Comment by leotsarev** [comment] 2018-12-28 12:09
@lahma we upgraded our setup to latest version in hope of fix. It doesn't help
Ok, we'll try

**Comment by lahma** [comment] 2018-12-29 09:14
Please enable logging at least on INFO level, this is now just guesswork with many different setups. Quartz shouldn't take any triggers other than in state WAITING, see https://github.com/quartznet/quartznet/blob/139aafa23728892b0a5ebf845ce28c3bfdb0bfe8/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L2513 . Blocked instances can transition back when cluster recovery kicks in, see https://github.com/quartznet/quartznet/blob/139aafa23728892b0a5ebf845ce28c3bfdb0bfe8/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L3075 .

**Comment by CassandraDied** [comment] 2019-01-10 13:46
@lahma 
Thanks for help.

We've enabled logging and found the following record:
`This scheduler instance (jobs.serv.su636815894934393290) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.`
Could this possibly be the thing that causes parallel running jobs?

**Comment by lahma** [comment] 2019-01-10 14:17
@CassandraDied so do you have nodes coming up and going down dynamically? having two running at the same time with same instance id will cause trouble, just like the logging indicates. The should never be two instances running at the same time with same id.

**Comment by CassandraDied** [comment] 2019-01-10 14:53
@lahma 
Well, yeah, we have deployments that could shut down nodes one by one and then turn them on again.
I guess this configuration option should not allow the same instance id on two different nodes

> ["quartz.scheduler.instanceId"] = "AUTO",
Isn't that so?

**Comment by lahma** [comment] 2019-01-10 15:32
It should not allow same id, that's what makes the warning quite peculier. Are there any exceptions before this?

**Comment by CassandraDied** [comment] 2019-01-10 15:46
No, no exceptions. The only strange thing is that there are a lot of records about failed instances. And it looks like after cluster manager founds a failed instance, it changes triggers to WAITING state, making possible to run them again while these scheduler instances and jobs aren't really failed.

Probably there is some issue with how often instances do Check In. Because we do not redeploy application every 3-10 minutes, and cluster manager finds failed instances this often.

**Comment by lahma** [comment] 2019-01-10 15:56
Job store's default ClusterCheckinMisfireThreshold is 7500ms . If you don't have cluster clocks synced within the limit can be reached. If clock sync cannot be achieved at this level you could try to tune this parameter to higher number, like 60000 (one minute).

**Comment by CassandraDied** [comment] 2019-01-10 16:31
I can't find ClusterCheckinMisfireThreshold property anywhere. Is it really presented in code?
And is there a way to adjust ClusterCheckinInterval?

**Comment by lahma** [comment] 2019-01-10 16:34
It's here:

https://github.com/quartznet/quartznet/blob/a5f191d14f844bc29b2838e837c671d544cffb3b/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L77

and here:

https://github.com/quartznet/quartznet/blob/a5f191d14f844bc29b2838e837c671d544cffb3b/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L163-L169

You can configure any property with setter via normal property configuration syntax, e.g.:

```
properties["quartz.jobStore.clusterCheckinInterval"] = 60_000.ToString();
```

**Comment by CassandraDied** [comment] 2019-01-21 11:19
So here are the results.
There is no evidences that changing `SqlServerDelegate` helped somehow.
Amount of “recovered” scheduler instances dropped dramatically after changing `clusterCheckinInterval` to one minute.

We still don't know the exact reason that cause so many scheduler instances become recovered.
We figured out that scheduler recovery mechanics isn't 100% accurate, sometimes it can mark a normally working scheduler as faulted, that leads to marking all triggers of that scheduler as “ready to be run” without actual stop of already fired jobs.

**Comment by lahma** [comment] 2020-07-21 07:42
I'm closing old issues which are "stuck", we can reopen if there's still reproducible problems with 3.1 beta series (there's been fixes to locking for example). Thanks for undestanding.

**Closed by lahma** 2020-07-21 07:42 UTC

**Comment by leotsarev** [comment] 2020-07-21 07:59
@lahma sorry, we didn't get back to you.
We found the problem in our setup was from CPU load — when some nodes are in 100% CPU, they skipped updating the store and other nodes considered this jobs lost and recover them by re-running. I suggest adding in documentation (near warning about time-sync) warning about "you should have enough free CPU, or Quartz will have problems".

**Comment by lahma** [comment] 2020-07-21 08:18
@leotsarev thanks for pinging back and the suggestion. I've updated the [tutorial](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/advanced-enterprise-features.html) and the new [configuration reference](https://www.quartz-scheduler.net/documentation/quartz-3.x/configuration/reference.html#clustering) to include the warning.

I hope Quartz is serving you well and please take the new 3.1 beta (or the upcoming RTM) for a spin!
