### ISSUE TITLE
Remove dependency on Common.Logging

### ISSUE THREAD

**Issue by lennygran** [quartznet/quartznet#310] opened 2015-11-07 22:59 UTC
Every project is different and having multiple logging libraries is not a good idea. Please remove this dependency so the logging can be done via a logging interface or simple lambda expression.

**Comment by roryprimrose** [comment] 2015-11-08 03:39
I'm not a fan of it either, although I totally understand the intention. I like the idea of an interface with perhaps a default implementation being to call down to Trace.XYZ.

**Comment by GieltjE** [comment] 2015-11-09 10:36
This has been fixed through bug #240 and in the quartznet-3 branche.

**Comment by lahma** [comment] 2015-11-09 10:38
Duplicate of  #240, let's continue discussion there.

**Closed by lahma** 2015-11-09 10:38 UTC
