### ISSUE TITLE
Can't build from Source

### ISSUE THREAD

**Issue by kabua** [quartznet/quartznet#826] opened 2020-02-12 21:01 UTC
Just down loaded Quarz.NET-3.0.7.zip. Unzipped it and tried to:
1) run build.cmd and got an error Path not found. 
2) Then I tried to build it from within VS2019 but the AssemblyInfo.cs file was missing. So I created an empty file.
3) Now I'm seeing 30 errors, Most are "Unable to locate repository containing directory '...'

What step(s) am I missing?

**Comment by lahma** [comment] 2020-02-13 06:25
This is a duplicate of https://github.com/quartznet/quartznet/issues/763 , please see discussion over there.

**Closed by lahma** 2020-02-13 06:25 UTC
