### ISSUE TITLE
Replace Common.Logging with LibLog

### ISSUE THREAD

**Issue by he-dev** [quartznet/quartznet#240] opened 2015-03-03 12:34 UTC
It's actually a quite useful framework if not the logger dependency. It would be great if there was a version without it.

**Comment by lahma** [comment] 2015-03-03 12:58
Could you please elaborate the problem you have with Quartz using a logging framework instead of inventing its own?

**Comment by x-t3ch** [comment] 2015-03-03 13:07
We use our own logging framework and find quartz shouldn't force us to use another system or load more assemblies then necessary. We also use a different configuration system then the app.config so we have to maintain two different configurations currently and provide a dummy configuration for the common.logger so that it stays quiet. The download of common.logger should be optional and quartz shouldn't log anything by itself but throw exceptions. The user of the framework should decide what is logged when and how.

**Comment by lahma** [comment] 2015-03-03 15:34
That's why you can just create your own delegating adapter and direct it to use your own logging infrastructure.

**Comment by madhon** [comment] 2015-03-04 08:54
What about moving from Common.Logging to LibLog ?

**Comment by lahma** [comment] 2015-03-04 09:40
@madhon that's an interesting idea. Probably well worth considering the grief we had with CL 3.0. I'll do some testing and a possibility for inclusion in 2.4 release.

**Comment by lahma** [comment] 2015-03-07 14:22
Can be done with 3.0 as LibLog does not support .NET 3.5.

**Comment by GieltjE** [comment] 2015-07-08 12:41
It would be awesome to be able to use a dummy logger, for our program we don't use the logging and CL is a pain to distribute (currently the latest update breaks it again).

**Comment by lahma** [comment] 2015-07-08 12:43
Yes this is already fixed in v3 branch. CL is no longer used and thus there should be no distribution pains (caused by CL).

**Comment by GieltjE** [comment] 2015-07-08 12:44
Will LibLog be a requirement?

**Comment by lahma** [comment] 2015-07-08 12:52
For Quartz yes, but it's not an actual binary library. It's just a c# source file included in the project and compiled into the resulting dll. So no extra dependency dll is produced.

**Closed** 2015-07-20 10:15 UTC
