### ISSUE TITLE
Add job to the runtime without restart Quartz

### ISSUE THREAD

**Issue by AdelSS04** [quartznet/quartznet#1092] opened 2021-01-26 12:45 UTC
Well, Iam using quartz to schedule sending mail, every user of my app could create more jobs to receive mail. What I want to do, is added the new job to run time of current schudeler. Here what am using: 
- Load the jobs into a List; 
- Loop the List and create the jobs if not exist; 
So I wanna know how to add new jobs.

**Comment by lahma** [comment] 2021-01-26 13:19
Closing as duplicate of https://stackoverflow.com/questions/65885507/add-job-to-quartez-at-runtime .

**Closed by lahma** 2021-01-26 13:19 UTC
