### ISSUE TITLE
package seems to break functional testing with a Microsoft.AspNetCore.TestHost.Testserver

### ISSUE THREAD

**Issue by ruwentos** [quartznet/quartznet#1136] opened 2021-03-23 14:08 UTC
I'm using Quartz like this in my code and everything works as expected:

```
services.AddQuartz(q =>
{
    q.SchedulerId = "CutOff-time-scheduler";
    
    q.UseMicrosoftDependencyInjectionScopedJobFactory(options =>
    {
        options.CreateScope = true;
        options.AllowDefaultConstructor = false;
    });

    q.ScheduleJob<SendEventIfMarketCutOffTimePassedJob>(trigger => trigger
        .WithIdentity("daily-trigger")
        .WithCronSchedule(configuration["CutOffTimeCronSchedule"])
        .WithDescription("triggers the 'SendEventIfMarketECutOffTimePassed' job every day")
        .StartNow()
    );
});

services.AddQuartzHostedService(options =>
{
    // when shutting down we want jobs to complete gracefully
    options.WaitForJobsToComplete = true;
});
```

At the same time there are a bunch of functional tests using an IClassFixture like this:

```
[Collection("Sequential")]
public class AssetFunctionalTest : IClassFixture<TestFixture>
{
    private readonly IMarketRepository _marketRepository;
    private readonly HttpClient _client;
    private const string AssetUrl = "/WENGRIN/MicroService-Asset/Asset";
    
    public AssetFunctionalTest(TestFixture fixture)
    {
        _client = fixture.Client;
        _marketRepository = fixture.MarketRepository;
    }
```
Where the TestFixture class creates a test server like this:

```
 protected TestFixture(string relativeTargetProjectParentDir)
{
    var startupAssembly = typeof(Startup).GetTypeInfo().Assembly;
    var contentRoot = GetProjectPath(relativeTargetProjectParentDir, startupAssembly);

    var configurationBuilder = new ConfigurationBuilder()
        .SetBasePath(contentRoot)
        .AddJsonFile("appsettings.Development.json");

    var webHostBuilder = new WebHostBuilder()
        .UseContentRoot(contentRoot)
        .ConfigureServices(InitializeServices)
        .UseConfiguration(configurationBuilder.Build())
        .UseEnvironment("Development")
        .UseStartup(typeof(Startup));

    // Create instance of test server
    _server = new TestServer(webHostBuilder);

    Client = _server.CreateClient();
    MarketRepository = _server.Services.CreateScope().ServiceProvider.GetService<IMarketRepository>();
    Client.BaseAddress = new Uri("http://localhost:44347");
    Client.DefaultRequestHeaders.Accept.Clear();
    Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
}
```

And cleans it up after one test class has finished running all tests.

```
public void Dispose()
{
    Client?.Dispose();
    _server?.Dispose();
}
```
When I start the tests, the first test class runs fine, but all others fail with the same error message while trying to create the test server.

**Message: 
    System.AggregateException : One or more errors occurred. (Cannot access a disposed object.
    Object name: 'LoggerFactory'.) (The following constructor parameters did not have matching fixture data: TestFixture fixture)
    ---- System.ObjectDisposedException : Cannot access a disposed object.
    Object name: 'LoggerFactory'.
    ---- The following constructor parameters did not have matching fixture data: TestFixture fixture
  Stack Trace: 
    ----- Inner Stack Trace #1 (System.ObjectDisposedException) -----
    LoggerFactory.CreateLogger(String categoryName)
    MicrosoftLoggingProvider.GetLogger(String name)
    LogProvider.GetLogger(String name)
    LogProvider.GetLogger(Type type, String fallbackTypeName)
    XMLSchedulingDataProcessor.ctor(ITypeLoadHelper typeLoadHelper)
    ContainerConfigurationProcessor.ctor(ITypeLoadHelper typeLoadHelper, IOptions`1 options)**

When I don't start the scheduler, the tests run fine again.

I'm using this version:
```
<PackageReference Include="Quartz" Version="3.2.4" />
<PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.2.4" />
<PackageReference Include="Quartz.Extensions.Hosting" Version="3.2.4" />
```

**Comment by lahma** [comment] 2021-03-23 16:28
Do you actually need Quartz in your tests, like does it make sense to add the hosted service? If you can skip adding that then Quartz won't be running and missing services, I think it has something to do that test case completes before Quartz initialization completes.

**Comment by ruwentos** [comment] 2021-03-23 16:38
I don't need it. But on the other hand it becomes a needed effort to switch the scheduler off before running the tests. Rather inconvenient.

**Comment by lahma** [comment] 2021-03-23 16:43
When I configure web application factory in tests I remove all IHostedServices from service collection that Startup populates as they are rarely needed, can be done in single place and is quite generic.

**Comment by ruwentos** [comment] 2021-03-23 17:07
I will think about it. Thank you very much.

**Comment by ruwentos** [comment] 2021-03-24 18:15
Perhaps this could help.

https://github.com/HangfireIO/Hangfire/issues/1099

**Comment by tomekpr** [comment] 2021-04-08 16:12
Hi,
I think I'm also facing a similar problem i.e. ObjectDisposedException when trying to access logger factory. If you don't care about logging information from your scheduler then you might be able to overwrite Quartz's logger with the following statement:

Quartz.Logging.LogContext.SetCurrentLogProvider(NullLoggerFactory.Instance);

This did the trick for me, however, this could be masking a bigger issue: scheduler isn't stopped correctly when running unit tests despite the fact it is being torn down after each test. Not sure if the problem is within scheduler, the way nunit runs async tests or somewhere else.

**Comment by lahma** [comment] 2021-08-01 07:26
I don't think there's much more to do here as it's more of a test configuration issue and probably always requires changes outside of the library, so closing. PRs and improvements of course welcome.

**Closed by lahma** 2021-08-01 07:26 UTC

**Comment by ITaluone** [comment] 2024-02-15 10:11
> When I configure web application factory in tests I remove all IHostedServices from service collection that Startup populates as they are rarely needed, can be done in single place and is quite generic.

This does the trick for me too. Thanks for this hint :)

**Comment by vvuk** [comment] 2025-02-14 17:31
Very old issue, but this had me scratching my head. FWIW, I don't think this is a "configuration issue" -- IMO adding Quartz.NET shouldn't suddenly break tests.

As a potential suggestion, the `CreateLogger` could be wrapped with a try/catch for ObjectDisposedException inside `MicrosoftLoggingProvider`. But that doesn't resolve the scheduler shutdown issue.
